apiVersion: v1
kind: Service
metadata:
  name: external-db-service
  namespace: application-namespace
spec:
  type: ExternalName
  externalName: my-database-service.database-namespace.svc.cluster.local
  ports:
  - port: 5432
