apiVersion: v1
kind: Service
metadata:
  name: my-database-service
  namespace: database-namespace
spec:
  selector:
    app: my-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
